# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0024_auto_20171215_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='pizzashop/', verbose_name='Изображение'),
        ),
    ]
