# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop', '0025_auto_20171216_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
    ]
